# Generated by Django 5.2.7 on 2025-11-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color_event',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='userevent',
            name='color_event',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
