# Generated by Django 5.2.7 on 2025-11-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_color_event_event_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='created_at',
        ),
    ]
